---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux
  namespace: k8s
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/biraderomkar/kubernetes_sot.git

